name: Amazon Scraper

on:
  push:                     # Runs on every push to the repo
    branches:
      - main
  schedule:                 # Runs on schedule
    - cron: "*/10 * * * *"  # Every 10 minutes
  workflow_dispatch:        # Allow manual run

permissions:
  contents: write           # Required so GitHub Actions can push changes

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Amazon Scraper
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python amazon_scraper.py

      - name: Commit updated CSV (only if changed)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add amazon_data.csv
          if ! git diff --cached --quiet; then
            git commit -m "Update scraped data [skip ci]"
            git push origin main
          else
            echo "No changes in CSV, skipping commit."
